[build]
  # Build command
  command = "npm run build"

  # Directory where built files are stored (Vite outputs to dist by default)
  publish = "dist"

  # Node.js version (optional but recommended)
  [build.environment]
    NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  [[redirects]]
  from = "/google264b8bc8d99342af.html"
  to = "/google264b8bc8d99342af.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"
